[tool.poetry]
name = "quackling"
version = "0.0.1"
description = "Quackling enables document-native generative AI applications"
license = "MIT"
authors = [
    "Panos Vagenas <pva@zurich.ibm.com>",
]
maintainers = [
    "Panos Vagenas <pva@zurich.ibm.com>",
    "Michele Dolfi <dol@zurich.ibm.com>",
    "Cesar Berrospi Ramis <ceb@zurich.ibm.com>",
    "Christoph Auer <cau@zurich.ibm.com>",
    "Peter Staar <taa@zurich.ibm.com>",
]
readme = "README.md"
homepage = "https://github.com/DS4SD/quackling"
repository = "https://github.com/DS4SD/quackling"
keywords = ["document", "PDF", "RAG", "generative AI", "chunking", "docling", "llama index"]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
    "Programming Language :: Python :: 3"
]
packages = [{ include = "quackling" }]

[tool.poetry.dependencies]
python = "^3.10"
docling-core = "^1.1.2"

llama-index-core = "^0.10.58"
docling = "^1.1.2"

#########
# extras:
#########
python-dotenv = { version = "^1.0.1", optional = true }
llama-index-embeddings-huggingface = { version = "^0.2.2", optional = true }
llama-index-llms-huggingface-api = { version = "^0.1.0", optional = true }
llama-index-vector-stores-milvus = { version = "^0.1.20", optional = true }
flagembedding = { version = "^1.2.10", optional = true }
jsonpath-ng = { version = "^1.6.1", optional = true }

[tool.poetry.extras]
examples = [
    "python-dotenv",
    "llama-index-embeddings-huggingface",
    "llama-index-llms-huggingface-api",
    "llama-index-vector-stores-milvus",
    "flagembedding",
    "jsonpath-ng",
]

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
ipywidgets = "^8.1.3"
ipykernel = "^6.29.4"
rich = "^13.7.1"
isort = "^5.13.2"
pre-commit = "^3.7.1"
nbqa = "^1.8.5"
flake8 = "^7.1.0"
mypy = "^1.10.1"
pytest = "^8.3.1"
python-semantic-release = "^7.32.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py310"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
py_version = 311

[tool.mypy]
pretty = true
# strict = true
no_implicit_optional = true
python_version = "3.10"

[[tool.mypy.overrides]]
module = [
    "pandas.*",
    "docling.*",
    "requests.*",
    "FlagEmbedding.*",
    "tabulate.*",
    "llama_index.*",
    "jsonpath_ng.*"
]
ignore_missing_imports = true

[tool.semantic_release]
# for default values check:
# https://github.com/python-semantic-release/python-semantic-release/blob/v7.32.2/semantic_release/defaults.cfg

version_source = "tag_only"
branch = "main"

# configure types which should trigger minor and patch version bumps respectively
# (note that they must be a subset of the configured allowed types):
parser_angular_allowed_types = "build,chore,ci,docs,feat,fix,perf,style,refactor,test"
parser_angular_minor_types = "feat"
parser_angular_patch_types = "fix,perf"
